### ISSUE TITLE
Run script on "startup" of new VM

### ISSUE THREAD

**Issue by dandunckelman** [lamw/instantclone-community-customization-scripts#1]
# Summary

We have a use-case where we'd like to run a "startup" script on a Windows (or any OS) VM as soon as the clone is ready.

Is there a hook for this?  VMware tools?

Since it's an instant clone, it's not following a typical poweron process.  So, I'm hoping there's an event I can hook into to run an arbitrary set of scripts.

I wasn't sure if this was the best place to ask, but I figured I'd start here.

Thanks

**Comment by lamw** [comment]
Please take a look at the blog post [here](https://www.virtuallyghetto.com/2018/04/new-instant-clone-architecture-in-vsphere-6-7-part-2.html) for more details, hopefully it should be clear once you've gone through it and some of the examples I've

**Comment by dandunckelman** [comment]
@lamw thanks.  I did read it.  Upon re-reading and discussion w/ others, I've come to find a way to apply what we want into our workflow.

I guess I thought there would be more of a "lifecycle hook" within the VM that could trigger some script(s).  It feels weird to run a script that "comes back to life" (post freeze) when the VM is cloned.  So, it works; it just doesn't feel intuitive.  I can accept that.

Thanks
